var searchData=
[
  ['o_20operation_20functions_0',['I/O Operation Functions',['../group___d_m_a___exported___functions___group2.html',1,'']]],
  ['ob_20boot_20ube_1',['FLASH OB Boot UBE',['../group___f_l_a_s_h___o_b___u_s_e_r___b_o_o_t___u_b_e.html',1,'']]],
  ['ob_20swap_20bank_2',['FLASH OB SWAP BANK',['../group___f_l_a_s_h___o_b___u_s_e_r___s_w_a_p___b_a_n_k.html',1,'']]],
  ['ob_20user_20type_3',['FLASH OB USER Type',['../group___f_l_a_s_h___o_b___u_s_e_r___type.html',1,'']]],
  ['observation_20registers_4',['Software Test Library Observation Registers',['../group___s_t_l___type.html',1,'']]],
  ['of_20stop_20bits_5',['UART Number of Stop Bits',['../group___u_a_r_t___stop___bits.html',1,'']]],
  ['of_20unitary_20conversion_20or_20sequence_20conversions_6',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['of_20view_7',['I2C Transfer Direction Master Point of View',['../group___i2_c___x_f_e_r_d_i_r_e_c_t_i_o_n.html',1,'']]],
  ['off_20block_20selection_8',['Memory shut-off block selection',['../group___p_w_r_ex___memory___shut___off.html',1,'']]],
  ['offset_20number_9',['ADC instance - Offset number',['../group___a_d_c___h_a_l___e_c___o_f_f_s_e_t___n_b.html',1,'']]],
  ['offset_20sign_10',['ADC Extended Offset Sign',['../group___a_d_c_ex___offset_sign.html',1,'']]],
  ['offstate_20selection_20for_20idle_20mode_20state_11',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['offstate_20selection_20for_20run_20mode_20state_12',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['on_20conversion_20data_13',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['on_20gpio_14',['Fast-mode Plus on GPIO',['../group___s_b_s___fast_mode_plus___g_p_i_o.html',1,'']]],
  ['on_20reset_15',['On Reset',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m1___r_s_t.html',1,'FLASH Option Bytes SRAM1 Erase On Reset'],['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m1__3___r_s_t.html',1,'FLASH Option Bytes SRAM1_3 Erase On Reset'],['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'FLASH Option Bytes SRAM2 Erase On Reset']]],
  ['on_20rx_20error_16',['UART Advanced Feature DMA Disable On Rx Error',['../group___u_a_r_t___d_m_a___disable__on___rx___error.html',1,'']]],
  ['one_20bit_20sampling_20method_17',['UART One Bit Sampling Method',['../group___u_a_r_t___one_bit___sampling.html',1,'']]],
  ['one_20pulse_20functions_18',['One Pulse functions',['../group___t_i_m_ex___exported___functions___group4.html',1,'Extended Timer Complementary One Pulse functions'],['../group___t_i_m___exported___functions___group5.html',1,'TIM One Pulse functions']]],
  ['one_20pulse_20mode_19',['TIM One Pulse Mode',['../group___t_i_m___one___pulse___mode.html',1,'']]],
  ['opamp_20aliased_20defines_20maintained_20for_20legacy_20purpose_20',['HAL OPAMP Aliased Defines maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___defines.html',1,'']]],
  ['opamp_20aliased_20macros_20maintained_20for_20legacy_20purpose_21',['HAL OPAMP Aliased Macros maintained for legacy purpose',['../group___h_a_l___o_p_a_m_p___aliased___macros.html',1,'']]],
  ['operation_20area_22',['FLASH Operation Area',['../group___f_l_a_s_h___operation___area.html',1,'']]],
  ['operation_20functions_23',['Operation Functions',['../group___d_m_a___exported___functions___group2.html',1,'I/O Operation Functions'],['../group___d_m_a_ex___exported___functions___group2.html',1,'Linked-List IO Operation Functions'],['../group___d_m_a_ex___exported___functions___group5.html',1,'Suspend and Resume Operation Functions']]],
  ['operation_20functions_24',['operation functions',['../group___i2_c___exported___functions___group2.html',1,'Input and Output operation functions'],['../group___e_x_t_i___exported___functions___group2.html',1,'IO operation functions'],['../group___g_p_i_o___exported___functions___group2.html',1,'IO operation functions'],['../group___u_a_r_t___exported___functions___group2.html',1,'IO operation functions']]],
  ['operation_20type_25',['FLASH Operation Type',['../group___f_l_a_s_h___operation___type.html',1,'']]],
  ['operational_20functions_26',['operational functions',['../group___i3_c___exported___functions___group5.html',1,'Controller operational functions.'],['../group___i3_c___exported___functions___group6.html',1,'Target operational functions.']]],
  ['option_20bytes_20boot_20configuration_27',['FLASH Option Bytes Boot configuration',['../group___f_l_a_s_h___o_b___b_o_o_t___c_o_n_f_i_g.html',1,'']]],
  ['option_20bytes_20boot_20lock_28',['FLASH Option Bytes Boot Lock',['../group___f_l_a_s_h___o_b___b_o_o_t___l_o_c_k.html',1,'']]],
  ['option_20bytes_20global_20trustzone_29',['FLASH Option Bytes Global TrustZone',['../group___f_l_a_s_h___o_b___u_s_e_r___t_z_e_n.html',1,'']]],
  ['option_20bytes_20nrst_5fstdby_30',['FLASH Option Bytes nRST_STDBY',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_a_n_d_b_y.html',1,'']]],
  ['option_20bytes_20nrst_5fstop_31',['FLASH Option Bytes nRST_STOP',['../group___f_l_a_s_h___o_b___u_s_e_r__n_r_s_t___s_t_o_p.html',1,'']]],
  ['option_20bytes_20sram1_20erase_20on_20reset_32',['FLASH Option Bytes SRAM1 Erase On Reset',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m1___r_s_t.html',1,'']]],
  ['option_20bytes_20sram1_5f3_20erase_20on_20reset_33',['FLASH Option Bytes SRAM1_3 Erase On Reset',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m1__3___r_s_t.html',1,'']]],
  ['option_20bytes_20sram2_20erase_20on_20reset_34',['FLASH Option Bytes SRAM2 Erase On Reset',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___r_s_t.html',1,'']]],
  ['option_20bytes_20usb_20power_20delivery_20configuration_35',['FLASH Option Bytes USB power delivery configuration',['../group___o_b___u_s_e_r___u_s_b_p_d___d_i_s.html',1,'']]],
  ['option_20bytes_20user_20bkpram_20ecc_20check_36',['FLASH Option Bytes User BKPRAM ECC check',['../group___f_l_a_s_h___o_b___u_s_e_r___b_k_p_r_a_m___e_c_c.html',1,'']]],
  ['option_20bytes_20user_20iwdg_20type_37',['FLASH Option Bytes User IWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___i_w_d_g___s_w.html',1,'']]],
  ['option_20bytes_20user_20sram1_20ecc_20check_38',['FLASH Option Bytes User SRAM1 ECC check',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m1___e_c_c.html',1,'']]],
  ['option_20bytes_20user_20sram2_20ecc_20check_39',['FLASH Option Bytes User SRAM2 ECC check',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m2___e_c_c.html',1,'']]],
  ['option_20bytes_20user_20sram3_20ecc_20check_40',['FLASH Option Bytes User SRAM3 ECC check',['../group___f_l_a_s_h___o_b___u_s_e_r___s_r_a_m3___e_c_c.html',1,'']]],
  ['option_20bytes_20user_20wwdg_20type_41',['FLASH Option Bytes User WWDG Type',['../group___f_l_a_s_h___o_b___u_s_e_r___w_w_d_g___s_w.html',1,'']]],
  ['option_20bytes_20vdd_20io_20hslv_42',['FLASH Option Bytes VDD IO HSLV',['../group___f_l_a_s_h___o_b___u_s_e_r___i_o___v_d_d___h_s_l_v.html',1,'']]],
  ['option_20bytes_20vddio2_20io_20hslv_43',['FLASH Option Bytes VDDIO2 IO HSLV',['../group___f_l_a_s_h___o_b___u_s_e_r___i_o___v_d_d_i_o2___h_s_l_v.html',1,'']]],
  ['option_20bytes_20write_20protection_20sectors_44',['FLASH Option Bytes Write Protection Sectors',['../group___f_l_a_s_h___o_b___write___protection___sectors.html',1,'']]],
  ['option_20definition_45',['OPTION DEFINITION',['../group___i3_c___d_y_n_a_m_i_c___a_d_d_r_e_s_s___o_p_t_i_o_n___d_e_f_i_n_i_t_i_o_n.html',1,'I3C DYNAMIC ADDRESS OPTION DEFINITION'],['../group___i3_c___o_p_t_i_o_n___d_e_f_i_n_i_t_i_o_n.html',1,'OPTION DEFINITION']]],
  ['option_20type_46',['FLASH Option Type',['../group___f_l_a_s_h___option___type.html',1,'']]],
  ['options_47',['I2C Sequential Transfer Options',['../group___i2_c___x_f_e_r_o_p_t_i_o_n_s.html',1,'']]],
  ['or_203_48',['TIM Group Channel 5 and Channel 1, 2 or 3',['../group___t_i_m___group___channel5.html',1,'']]],
  ['or_20differential_20ending_49',['Channel - Single or differential ending',['../group___a_d_c___h_a_l___e_c___c_h_a_n_n_e_l___s_i_n_g_l_e___d_i_f_f___e_n_d_i_n_g.html',1,'']]],
  ['or_20disabled_20status_50',['or Disabled Status',['../group___r_c_c___a_h_b1___peripheral___clock___enable___disable___status.html',1,'AHB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b2___peripheral___clock___enable___disable___status.html',1,'AHB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_h_b4___peripheral___clock___enable___disable___status.html',1,'AHB4 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b1___peripheral___clock___enable___disable___status.html',1,'APB1 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b2___peripheral___clock___enable___disable___status.html',1,'APB2 Peripheral Clock Enabled or Disabled Status'],['../group___r_c_c___a_p_b3___peripheral___clock___enable___disable___status.html',1,'APB3 Peripheral Clock Enabled or Disabled Status']]],
  ['or_20sequence_20conversions_51',['ADC sequencer end of unitary conversion or sequence conversions',['../group___a_d_c___e_o_c_selection.html',1,'']]],
  ['or_20stop_20mode_52',['I2C Start or Stop Mode',['../group___i2_c___s_t_a_r_t___s_t_o_p___m_o_d_e.html',1,'']]],
  ['oscillator_20type_53',['Oscillator Type',['../group___r_c_c___oscillator___type.html',1,'']]],
  ['ossi_20offstate_20selection_20for_20idle_20mode_20state_54',['TIM OSSI OffState Selection for Idle mode state',['../group___t_i_m___o_s_s_i___off___state___selection__for___idle__mode__state.html',1,'']]],
  ['ossr_20offstate_20selection_20for_20run_20mode_20state_55',['TIM OSSR OffState Selection for Run mode state',['../group___t_i_m___o_s_s_r___off___state___selection__for___run__mode__state.html',1,'']]],
  ['otp_20blocks_56',['FLASH OTP blocks',['../group___f_l_a_s_h___o_t_p___blocks.html',1,'']]],
  ['out_20value_57',['UART polling-based communications time-out value',['../group___u_a_r_t___time_out___value.html',1,'']]],
  ['output_58',['Output',['../group___r_c_c___p_l_l1___clock___output.html',1,'RCC PLL1 Clock Output'],['../group___r_c_c___p_l_l2___clock___output.html',1,'RCC PLL2 Clock Output']]],
  ['output_20compare_20and_20pwm_20modes_59',['TIM Output Compare and PWM Modes',['../group___t_i_m___output___compare__and___p_w_m__modes.html',1,'']]],
  ['output_20compare_20functions_60',['Output Compare functions',['../group___t_i_m_ex___exported___functions___group2.html',1,'Extended Timer Complementary Output Compare functions'],['../group___t_i_m___exported___functions___group2.html',1,'TIM Output Compare functions']]],
  ['output_20compare_20idle_20state_61',['Output Compare Idle State',['../group___t_i_m___output___compare___n___idle___state.html',1,'TIM Complementary Output Compare Idle State'],['../group___t_i_m___output___compare___idle___state.html',1,'TIM Output Compare Idle State']]],
  ['output_20compare_20polarity_62',['Output Compare Polarity',['../group___t_i_m___output___compare___n___polarity.html',1,'TIM Complementary Output Compare Polarity'],['../group___t_i_m___output___compare___polarity.html',1,'TIM Output Compare Polarity']]],
  ['output_20compare_20state_63',['Output Compare State',['../group___t_i_m___output___compare___n___state.html',1,'TIM Complementary Output Compare State'],['../group___t_i_m___output___compare___state.html',1,'TIM Output Compare State']]],
  ['output_20enable_64',['TIM Automatic Output Enable',['../group___t_i_m___a_o_e___bit___set___reset.html',1,'']]],
  ['output_20fast_20state_65',['TIM Output Fast State',['../group___t_i_m___output___fast___state.html',1,'']]],
  ['output_20operation_20functions_66',['Input and Output operation functions',['../group___i2_c___exported___functions___group2.html',1,'']]],
  ['output_20source_67',['Low Speed Microcontroller Clock Output Source',['../group___r_c_c_ex___l_s_c_o___clock___source.html',1,'']]],
  ['over_20sampling_68',['UART Over Sampling',['../group___u_a_r_t___over___sampling.html',1,'']]],
  ['overrun_20behavior_20on_20conversion_20data_69',['ADC group regular - Overrun behavior on conversion data',['../group___a_d_c___h_a_l___e_c___r_e_g___o_v_r___d_a_t_a___b_e_h_a_v_i_o_r.html',1,'']]],
  ['overrun_20disable_70',['UART Advanced Feature Overrun Disable',['../group___u_a_r_t___overrun___disable.html',1,'']]],
  ['oversampling_20data_20shift_71',['Oversampling - Data shift',['../group___a_d_c___h_a_l___e_c___o_v_s___s_h_i_f_t.html',1,'']]],
  ['oversampling_20discontinuous_20mode_72',['Oversampling - Discontinuous mode',['../group___a_d_c___h_a_l___e_c___o_v_s___d_i_s_c_o_n_t___m_o_d_e.html',1,'']]],
  ['oversampling_20oversampling_20scope_20for_20adc_20group_20regular_73',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]],
  ['oversampling_20ratio_74',['Oversampling - Ratio',['../group___a_d_c___h_a_l___e_c___o_v_s___r_a_t_i_o.html',1,'']]],
  ['oversampling_20scope_20for_20adc_20group_20regular_75',['Oversampling - Oversampling scope for ADC group regular',['../group___a_d_c___h_a_l___e_c___o_v_s___s_c_o_p_e___r_e_g.html',1,'']]],
  ['own_20activity_20state_76',['OWN ACTIVITY STATE',['../group___i3_c___o_w_n___a_c_t_i_v_i_t_y___s_t_a_t_e.html',1,'']]],
  ['own_20address2_20masks_77',['I2C Own Address2 Masks',['../group___i2_c___o_w_n___a_d_d_r_e_s_s2___m_a_s_k_s.html',1,'']]]
];
